// web/src/app/portfolio/page.tsx

import Card from "../components/card";
import CardInfo from "../lib/card";

export default function Portfolio() {

    const items: CardInfo[] = [
        new CardInfo(1, "Personal Website", "This project stores the code that runs https://www.ben-hilger.com", "https://github.com/Ben-Hilger/website"),
        new CardInfo(2, "Advent of Code", "This project stores the code that I write to solve advent of code problems (https://adventofcode.com/)", "https://github.com/Ben-Hilger/advent-of-code"),
        new CardInfo(3, "NVIM Config", "This project stores my current configuring for nvim, a terminal-based editor I use for perosnal projects", "https://github.com/Ben-Hilger/nvim-config"), 
        new CardInfo(4, "Language Basics", "This project is to store the basics of programming languages I'm currently learning.", "https://github.com/Ben-Hilger/language-basics"),
        new CardInfo(5, "LeetCode", "This project stores solutions I've written for different LeetCode problems", "https://github.com/Ben-Hilger/LeetCode"),
        new CardInfo(6, "Data Structures", "Here I've taken time to implement different data structures, currently in C, from scratch to gain a deeper understanding of the underlying logic", "https://github.com/Ben-Hilger/data-structures"),
    ];

    function getPortfolioItems() {

        return items.map((item: CardInfo) => {
            return (
                <Card
                    key={item.id}
                    title={item.title}
                    description={item.description}
                    link={item.link}
                />
            );
        });
    }

    return (
        <main className="portfolio-list h-100 p-2 background-inherit">
            { getPortfolioItems() }
        </main>
    );
}

// web-nuxt/pages/portfolio.vue
<template>
    <main class="grid grid-cols-3 h-100 p-2 background-inherit gap-2">
        <Card v-for="(portfolioItem, index) in portfolioItems" 
            v-bind:key="index"
            v-bind:title="portfolioItem.title"
            v-bind:description="portfolioItem.description"
            v-bind:target="portfolioItem.target"
            v-bind:link="portfolioItem.link"
        />
    </main>
</template>


<script setup lang="ts">
    type PortfolioInfo = {
        title: string,
        description: string,
        link: string,
        target: string
    }

    const portfolioItems: PortfolioInfo[] = [
        {title: "Personal Website", description: "This project stores the code that runs https://www.ben-hilger.com", link: "https://github.com/Ben-Hilger/website", target: "_blank"},
        {title: "Advent of Code", description: "This project stores the codee that I write to solve advent of code problems (https://adventofcode.com/)", link: "https://github.com/Ben-Hilger/advent-of-code", target: "_blank"},
        {title: "NVIM Config", description: "This project stores my current configuation for neovim, a terminal-based editor I use for personal projects", link: "https://ghithub.com/Ben-Hilger/nvim-config", target: "_blank"},
        {title: "LeetCode", description: "This project stores solutions that I've written for different LeetCode problems", link: "https://github.com/Ben-Hilger/LeetCode", target: "_blank"}
    ];


</script>
