// web-nuxt/components/Card.vue
<template>
    <div v-bind:class="{'cursor-pointer': link}" 
        class="border rounded border-black p-2 m-2"
        v-on:click="navigateTo">
        <b class="text-lg">{{ title }}</b>
        <div v-if="description">{{ description }}</div>
    </div>
</template>

<script setup lang="ts">

    interface Props {
        title: string,
        description?: string,
        link?: string, 
        target?: string
    }

    const props = defineProps<Props>()

    function navigateTo() {
        if (!props.link) {
            return;
        }
        window.open(props.link, props.target ?? "_self");
    }
</script>

// web/src/app/components/card.tsx
'use client';

interface CardProps {
    title: string,
    description: string,
    link?: string|null
    target?: string|null
}

export default function Card(props: CardProps) {

    function navigateTo() {
       if (!props.link) {
           return;
       }
       window.open(props.link, props.target ?? "_blank");
    }

    function getClasses() {
        let base = "border-01 border-rounded p-1 m-1";
        if (props.link) {
            base += " cursor-pointer";
        }
        return base;
    }

    return (
    <div className={ getClasses() } onClick={() => { navigateTo() }}>
        <b className="text-lg">{ props.title }</b>
        <p>{ props.description }</p>
    </div>
  );
}
